Task6 rspec
maksemuz/movies_rb pull request #1
Opened 2016-10-24 13:14 UTC by maksemuz

all but the last point about choice

2016-10-24 15:09 UTC, zverok requested changes

2016-10-24 15:09 UTC, zverok commented on movie.rb
> +    end
а как же 4 разных класса фильмов? :(

2016-10-24 15:09 UTC, zverok commented on netflix.rb
> +    @price = {"ancient" => 1,"classic" => 1.5,"modern" => 3,"new" => 5}
Это о себе классы фильмов должны знать.

2016-10-24 15:09 UTC, zverok commented on netflix.rb
> +    return films[to_watch]
`return` лишний

2016-10-24 15:09 UTC, zverok commented on netflix.rb
> +    films = self.filter(parameters)
`self` лишний

2016-10-24 15:09 UTC, zverok commented on netflix.rb
> +    to_watch = Random.new.rand(0...films.size-1)
вместо этого можно просто `films.sample`

2016-10-24 15:09 UTC, zverok commented on netflix.rb
> +    movie = self.all.find { |val| val.title == movie_name}
а если не нашлось фильма?..

2016-10-24 15:09 UTC, zverok commented on spec/netflix_spec.rb
> +  movie = "The Terminator"
Используй `let` и `subject` http://betterspecs.org/ru/#subject

2016-10-24 15:09 UTC, zverok commented on theatre.rb
> +    end
А как бы эту логику в константу красивую вынести, а?

2016-10-24 15:09 UTC, zverok commented on theatre.rb
> +    end
...и ту же красивую константу тут использовать

2016-10-24 20:19 UTC, maksemuz commented on movie.rb
> +    end
@zverok 4 типа, как завещано.
Надо сделать отдельные классы для каждого?

2016-10-24 20:24 UTC, maksemuz commented on netflix.rb
> +    films = self.filter(parameters)
@zverok почему self лишний? как без него обойтись?

2016-10-24 20:36 UTC, zverok commented on movie.rb
> +    end
Конешн. Тип = класс.

2016-10-24 20:36 UTC, zverok commented on netflix.rb
> +    films = self.filter(parameters)
Просто `filter(...)` написать, без `self.` :)

2016-10-24 20:49 UTC, maksemuz commented on netflix.rb
> +    to_watch = Random.new.rand(0...films.size-1)
@zverok поправил

2016-10-24 20:49 UTC, maksemuz commented on netflix.rb
> +    return films[to_watch]
@zverok поправил

2016-10-24 21:08 UTC, maksemuz commented on netflix.rb
> +    movie = self.all.find { |val| val.title == movie_name}
@zverok добавил raise

2016-10-24 21:12 UTC, maksemuz commented on netflix.rb
> +    films = self.filter(parameters)
да, точно, так же работает.
совсем забыл

2016-10-25 09:09 UTC, maksemuz commented on movie.rb
> +    end
я правильно понимаю, что родителем для них будет MovieCollection?

2016-10-25 09:09 UTC, maksemuz commented on movie.rb
> +    end
это первое, что приходит в голову

2016-10-25 09:15 UTC, zverok commented on movie.rb
> +    end
Почему?.. Наследование — нужно для описания «частных случаев» (т.е. базовый класс Animal, частный случай с более детально описанным поведением — Dog). AncientMovie — частный случай просто Movie

2016-10-25 09:46 UTC, maksemuz commented on movie.rb
> +    end
Родитель MovieCollection потому, что как в новых условиях инициализировать MovieCollection?
Сейчас он использует класс Movie для заполнения, а если сделать 4 частных случая Movie, то как их собрать в коллекцию?
Делать 4 объекта MovieCollection для каждого типа?
Мне кажется, что получается усложнение конструкции.

2016-10-25 10:02 UTC, zverok commented on movie.rb
> +    end
> Сейчас он использует класс Movie для заполнения, а если сделать 4 частных случая Movie, то как их собрать в коллекцию?

Ну вот прям так — в коллекции, в одном массиве, лежат фильмы всех четырёх типов. Кто их создаёт — другой вопрос, может сама коллекция, может базовый класс (ты вызываешь специально сделанный тобой метод `Movie.create(data)`, а он возвращает объект одного из производных классов.

2016-10-25 11:29 UTC, maksemuz commented on movie.rb
> +    end
То есть я правильно рассуждаю про 4 объекта?
Если нет, то я не понимаю, как в MovieCollection использовать каждый класс из этих 4х

2016-10-25 11:30 UTC, maksemuz commented on movie.rb
> +    end
И что должно получиться в итоге

2016-10-31 10:40 UTC, zverok requested changes
А спеки для самих фильмов и их поведения? В т.ч. для `Movie.create`?

2016-10-31 10:40 UTC, zverok commented on ancient_movie.rb
> +  attr_reader :price, :output, :period, :link, :title, :year, :country, :date, :genre, :duration, :rating, :director, :main_actors, :collection
Зачем?

2016-10-31 10:40 UTC, zverok commented on ancient_movie.rb
> +    @price = 1
Это константа должна быть

2016-10-31 10:40 UTC, zverok commented on ancient_movie.rb
> +    @period = 'ancient'
Это можно сделать методом, вычисляющим название периода из названия класса.

2016-10-31 10:40 UTC, zverok commented on ancient_movie.rb
> +    @output = "#{self.title} — старый фильм (#{self.year} год)"
Это можно сделать методом (не стоит хранить в переменных то что можно вычислить из других переменных — кроме случаев, когда повторно вычислять очень-очень дорого)

2016-10-31 10:40 UTC, zverok commented on classic_movie.rb
> +    @output = "#{self.title} — классический фильм, режиссёр #{self.director} (#{@films})"
Длинно же будет. В задании предполагается, что вывод будет что-то вроде `"... (ещё 10 его фильмов в топе)"` — в смысле, вот так прямо словами «ещё 10»

2016-10-31 10:40 UTC, zverok commented on ancient_movie.rb
> +    @output = "#{self.title} — старый фильм (#{self.year} год)"
И название странное (потому что может быть и существительным, и глаголом «вывести» — кого вывести? куда вывести?), лучше description или long_title

2016-10-31 10:40 UTC, zverok commented on movie.rb
> +    end
в большинстве случаев `self.` лишний :)

2016-10-31 10:40 UTC, zverok commented on movie.rb
> +    end
Тут бы `case` неплохо подошёл

2016-10-31 10:40 UTC, zverok commented on netflix.rb
> +    puts "You've paid #{amount}.\nYour balance is: 10 starter + #{amount} = #{@money}"
Лучше такое не класть в классы с логикой. (В крайнем случае, если хочется, можно использовать `logger`, который можно заглушить или перенаправить в файл) Классы с логикой должны заниматься, you know, логикой.

2016-10-31 10:40 UTC, zverok commented on netflix.rb
> +    puts "Price is #{to_watch.price}. Now your balance is: #{@money - to_watch.price}"
А баланс после этого уменьшится?.. Мне кажется, нет :) Попробуй три раза вызвать `show` и посмотреть что будет :)

2016-10-31 10:40 UTC, zverok commented on netflix.rb
> +    raise 'There is no such film in our collection. Sorry.' if not movie
Лучше выбирать правильный класс ошибки (например, ArgumentError), и сообщение об ошибке лучше делать информативным — вместо «such movie» — «кина с таким-то названием»

2016-10-31 10:40 UTC, zverok commented on new_movie.rb
> +    if ( how_long.size == "1" or how_long.first == "1" ) and how_long.last == "1"
Используй `||` и `&&`, у and и or [другой смысл](http://zverok.github.io/blog/2016-02-23-control-flow.html)

2016-10-31 10:40 UTC, zverok commented on new_movie.rb
> +    end
Хорошо что ты об этом задумался, но давай попробуем:
а) вынести в отдельный метод
б) работать с числами, а не со строками (оператор `%` — остаток от деления — тебе поможет, и ranges тоже)

2016-10-31 10:40 UTC, zverok commented on theatre.rb
> +    @schedule = {(8...12) => @morning_films,(12...18) => @noon_films, (18..24) => @evening_films }
Хорошо бы всю эту логику (какому периоду какие фильтры соответствуют) в константу положить. А выбирать фильмы на ходу.

2016-10-31 16:32 UTC, maksemuz commented on ancient_movie.rb
> +  attr_reader :price, :output, :period, :link, :title, :year, :country, :date, :genre, :duration, :rating, :director, :main_actors, :collection
зачем что, attr_reader? без него никак. можно уменьшить число атрибутов, но совсем убрать нельзя

2016-10-31 17:10 UTC, maksemuz commented on ancient_movie.rb
> +    @price = 1
исправил

2016-10-31 17:31 UTC, maksemuz commented on ancient_movie.rb
> +    @period = 'ancient'
сделал вот такой метод во все 4 наследника:
`  def period
    self.class.name.split("M")[0].downcase
  end`

2016-10-31 17:47 UTC, maksemuz commented on classic_movie.rb
> +    @output = "#{self.title} — классический фильм, режиссёр #{self.director} (#{@films})"
у них там средний топ не более 5
то есть все эти вычисления заменить на простую фразу "ещё 10 его фильмов в спике"?

2016-10-31 17:56 UTC, maksemuz commented on netflix.rb
> +    puts "Price is #{to_watch.price}. Now your balance is: #{@money - to_watch.price}"
баланс не уменьшится, это я понял сразу
но я предположил, что это реализуется как-то отдельно, каким-то классом пользовательских данных например
то есть выходит за рамки задания
но я понял, сделаю

2016-10-31 17:59 UTC, maksemuz commented on netflix.rb
> +    puts "You've paid #{amount}.\nYour balance is: 10 starter + #{amount} = #{@money}"
тогда просто убрать из проекта пополнение?
будет просто платеж
```
def pay(amount)
  @amount = amount
end
```

2016-10-31 21:33 UTC, zverok commented on ancient_movie.rb
> +  attr_reader :price, :output, :period, :link, :title, :year, :country, :date, :genre, :duration, :rating, :director, :main_actors, :collection
Так одинаковые ж аттрибуты, почему их в родителськом классе не определить?

2016-10-31 21:33 UTC, zverok commented on ancient_movie.rb
> +    @period = 'ancient'
а) больно хитро, мне кажется. почему не `sub('Movie', '')`?
б) зачем во все четыре наследника, а не в родителя?

2016-10-31 21:34 UTC, zverok commented on classic_movie.rb
> +    @output = "#{self.title} — классический фильм, режиссёр #{self.director} (#{@films})"
нет. не на простую фразу, а на количество фильмов (1, 2, 3, 5, сколько их там реально)

2016-10-31 21:34 UTC, zverok commented on netflix.rb
> +    puts "Price is #{to_watch.price}. Now your balance is: #{@money - to_watch.price}"
да нет, чего ж отдельно. если у нас `pay` увеличивает баланс, то `show` должен уменьшать, логично?

2016-10-31 21:35 UTC, zverok commented on netflix.rb
> +    puts "You've paid #{amount}.\nYour balance is: 10 starter + #{amount} = #{@money}"
что значит убрать пополнение? `@money += amount` совершенно логично, а вот `puts` тут ни к чему

2016-11-01 05:45 UTC, maksemuz commented on netflix.rb
> +    puts "Price is #{to_watch.price}. Now your balance is: #{@money - to_watch.price}"
логично, он и уменьшает. Но в пределах одного вызова спеки. То есть neflix_spec.rb отработал, и история нигде не сохраняется.

2016-11-01 05:47 UTC, maksemuz commented on netflix.rb
> +    puts "Price is #{to_watch.price}. Now your balance is: #{@money - to_watch.price}"
если после pay вызвать show 3 раза, то баланс уменьшится

2016-11-01 06:28 UTC, maksemuz commented on ancient_movie.rb
> +    @output = "#{self.title} — старый фильм (#{self.year} год)"
исправил вот так:
```
 def long_title
    "#{self.title} — старый фильм (#{self.year} год)"
  end
```

2016-11-01 06:30 UTC, maksemuz commented on classic_movie.rb
> +    @output = "#{self.title} — классический фильм, режиссёр #{self.director} (#{@films})"
исправил

2016-11-01 06:31 UTC, maksemuz commented on movie.rb
> +    end
исправли

2016-11-01 06:33 UTC, maksemuz commented on netflix.rb
> +    puts "You've paid #{amount}.\nYour balance is: 10 starter + #{amount} = #{@money}"
убрал строку с puts

2016-11-01 06:33 UTC, maksemuz commented on new_movie.rb
> +    if ( how_long.size == "1" or how_long.first == "1" ) and how_long.last == "1"
исправил

2016-11-01 06:35 UTC, maksemuz commented on ancient_movie.rb
> +  attr_reader :price, :output, :period, :link, :title, :year, :country, :date, :genre, :duration, :rating, :director, :main_actors, :collection
убрал attr_reader из наследников

2016-11-01 06:40 UTC, maksemuz commented on ancient_movie.rb
> +    @period = 'ancient'
про sub совсем забыл
вот такое в родителе:
```
  def period
    self.class.name.sub(/Movie/,'').downcase
  end
```

2016-11-01 10:56 UTC, zverok commented on netflix.rb
> +    puts "Price is #{to_watch.price}. Now your balance is: #{@money - to_watch.price}"
Разве? А какая строчка уменьшает текущий баланс?

2016-11-01 11:16 UTC, maksemuz commented on netflix.rb
> +    puts "Price is #{to_watch.price}. Now your balance is: #{@money - to_watch.price}"
Да, понял.
Оно просто пишет, что баланс уменьшен, но не уменьшает его.
Добавил вот это:
```
@money -= to_watch.class::PRICE
```

2016-11-01 12:11 UTC, maksemuz commented on movie.rb
> +    end
переделал вот в такой кейс:

```
    case year.to_i
      when (1900...1945)
        AncientMovie.new(link, title, year, country, date, genre, duration, rating, director, main_actors, collection)
      when (1945...1968)
        ClassicMovie.new(link, title, year, country, date, genre, duration, rating, director, main_actors, collection)
      when (1968...2000)
        ModernMovie.new(link, title, year, country, date, genre, duration, rating, director, main_actors, collection)
      else
        NewMovie.new(link, title, year, country, date, genre, duration, rating, director, main_actors, collection)
    end
```

2016-11-01 13:26 UTC, maksemuz commented on netflix.rb
> +    raise 'There is no such film in our collection. Sorry.' if not movie
исправил вот так:
```
raise ArgumentError, "There is no film named #{movie_name} in our collection. Sorry." if not movie
```

2016-11-03 16:44 UTC, maksemuz commented on new_movie.rb
> +    end
переделал вот так:
```
  def get_word(number)
    if number % 10 == 1 && !(10..20).include?(number)
      "год"
    elsif (2..4).include?(number) && !(12..14).include?(number)
      "года"
    else
        "лет"
    end
  end

  def long_title
    how_long = (Date.today.year - self.year)
    "#{self.title} — новинка, вышло #{Date.today.year - self.year} #{get_word(how_long)} назад!"
  end
```

2016-11-03 17:02 UTC, maksemuz commented on theatre.rb
> +    @schedule = {(8...12) => @morning_films,(12...18) => @noon_films, (18..24) => @evening_films }
в константУ или в константЫ ?

2016-11-03 17:04 UTC, maksemuz commented on theatre.rb
> +    @schedule = {(8...12) => @morning_films,(12...18) => @noon_films, (18..24) => @evening_films }
вот так например:
```
MORNING := filter(period: 'ancient')
NOON := filter(genre: 'Adventure') + filter(genre: 'Comedy')
EVENING := filter(genre: 'Drama') + filter(genre: 'Horror')
```

2016-11-03 17:11 UTC, maksemuz commented on theatre.rb
> +    @schedule = {(8...12) => @morning_films,(12...18) => @noon_films, (18..24) => @evening_films }
я не понимаю, как можно логику и вычисления засунуть в константу

2016-11-07 09:47 UTC, zverok requested changes

2016-11-07 09:47 UTC, zverok commented on ancient_movie.rb
> +  end
Зачем нам этот дополнительный конструктор? Что полезного он делает?

2016-11-07 09:47 UTC, zverok commented on classic_movie.rb
> +    @films = @collection.filter(director: self.director).take(10).map { |movie| movie.title}
Зачем мы создаём здесь instance variable?

2016-11-07 09:47 UTC, zverok commented on movie_collection.rb
> +      memo.find_all { |row| row.matches?(key,val) } }
:+1:

2016-11-07 09:47 UTC, zverok commented on movie_collection.rb
>                       .map{|k,v| [k, v.count] }
:+1:

2016-11-07 09:47 UTC, zverok commented on movie_collection.rb
> +    rate_max = films.sort_by { |film| film.send(:rating) }.last.rating.to_f
`minmax_by(&:rating)` ;)

2016-11-07 09:47 UTC, zverok commented on movie_collection.rb
> +    films.find_all { |movie| movie.rating.to_f >= rate}.sample
Ну, можно и так :) но в принципе достаточно было бы `films.sort_by { |f| rating * rand }.last` ;)

2016-11-07 09:47 UTC, zverok commented on netflix.rb
> +    @money -= to_watch.class::PRICE
Чтобы не писать всё время `.class::PRICE`, можно в базовом классе `Movie` единожды определить метод `price`, который будет это делать за тебя

2016-11-07 09:47 UTC, zverok commented on new_movie.rb
> +    end
Смотри:
```ruby
return 'лет' if (11..19).include?(years)

case years % 10
when 1
when 2..4
else
end
```

2016-11-07 09:47 UTC, zverok commented on spec/ancient_spec.rb
> +  puts "Title: \"#{film.title}\", Year: #{film.year}, Price: #{film.class::PRICE}"
Используй `let` и `subject`! Не клади переменные просто так внутрь `describe`, тесты не будут независимыми!

2016-11-07 09:47 UTC, zverok commented on spec/ancient_spec.rb
> +    expect(film.year).to be <= 1945
Идеальный тест всегда содержит один `expect`. С гемом `rspec-its` можно вообще вот так:
```ruby
it { is_expected.to be_an AncientMovie }
its(:year) { is_expected.to be <= 1945 }
...
```

2016-11-07 09:47 UTC, zverok commented on spec/netflix_spec.rb
> +    expect(netflix.money) == "Your balance: $#{amount}"
1. Что это за `==` вместо `.to eq`?
2. У нас правда `money` выдаёт текстовую строку вместо текущегок количества денег?..

2016-11-07 09:59 UTC, maksemuz commented on classic_movie.rb
> +    @films = @collection.filter(director: self.director).take(10).map { |movie| movie.title}
исправил на `films`

2016-11-07 10:00 UTC, maksemuz commented on movie_collection.rb
> +    films.find_all { |movie| movie.rating.to_f >= rate}.sample
исправить на твой вариант или оставить как есть?

2016-11-07 10:09 UTC, maksemuz commented on netflix.rb
> +    @money -= to_watch.class::PRICE
сделал вот такой метод в Movie:
```
  def price
    self.class::PRICE
  end
```
и везде, где вызывается, заменил на object.price

2016-11-07 10:15 UTC, maksemuz commented on new_movie.rb
> +    end
хороший прием - вынести (11..19) за пределы кейса
исправил

2016-11-07 10:18 UTC, maksemuz commented on spec/netflix_spec.rb
> +    expect(netflix.money) == "Your balance: $#{amount}"
1 - исправил
2 - нет, видимо была раньше. Убрал из проверки.

2016-11-07 10:26 UTC, maksemuz commented on movie_collection.rb
> +    rate_max = films.sort_by { |film| film.send(:rating) }.last.rating.to_f
исправил вот так:
```
    rate_min = films.min_by(&:rating).rating.to_f
    rate_max = films.max_by(&:rating).rating.to_f
```

2016-11-07 10:52 UTC, zverok commented on classic_movie.rb
> +    @films = @collection.filter(director: self.director).take(10).map { |movie| movie.title}
я бы спрятал эту строчку в отдельный приватный метод, вообще говоря. Ну и кстати непонятно зачем там take/map

2016-11-07 10:56 UTC, maksemuz commented on ancient_movie.rb
> +  end
забыл убрать после экспериментов
исправил

2016-11-07 10:57 UTC, maksemuz commented on movie_collection.rb
> +    films.find_all { |movie| movie.rating.to_f >= rate}.sample
@zverok ?

2016-11-07 11:14 UTC, zverok commented on movie_collection.rb
> +    rate_max = films.sort_by { |film| film.send(:rating) }.last.rating.to_f
А зачем `.to_f`, к слову?

2016-11-07 11:14 UTC, zverok commented on movie_collection.rb
> +    films.find_all { |movie| movie.rating.to_f >= rate}.sample
да оставляй

2016-11-07 11:20 UTC, maksemuz commented on movie_collection.rb
> +    rate_max = films.sort_by { |film| film.send(:rating) }.last.rating.to_f
потому что на выходе String
```
rate_min = films.min_by(&:rating).rating
```
вот такая ошибка:
```
movie_collection.rb:43:in `rand': no implicit conversion of String into Integer (TypeError)
```

2016-11-07 11:25 UTC, maksemuz commented on classic_movie.rb
> +    @films = @collection.filter(director: self.director).take(10).map { |movie| movie.title}
```take/map``` там осталось от варианта, где перечислялись фильмы в скобках, вместо "еще N фильмов"
исправил, теперь вот так:
```films = @collection.filter(director: self.director)```
а зачем отдельный метод? эта информация же не нужна нигде, кроме ```long_title```

2016-11-07 11:29 UTC, maksemuz commented on movie_collection.rb
> +    rate_max = films.sort_by { |film| film.send(:rating) }.last.rating.to_f
поправил в Movie:
```@rating = rating.to_f```

2016-11-09 09:36 UTC, zverok approved these changes

2016-11-09 09:49 UTC, merged