Added cash_box.rb module
maksemuz/movies_rb pull request #2
Opened 2016-11-17 07:45 UTC by maksemuz

Modified:
Netflix, Theatre, netflix_spec, theatre_spec

2016-11-18 13:06 UTC, zverok requested changes

2016-11-18 13:06 UTC, zverok commented on cash_box.rb
> +  def buy_ticket(movie_name)
Нет, мы же обсуждали — касса занимается только делами кассы, ей всё равно, подключат её к кинотеатру или автозаправке.

2016-11-18 13:06 UTC, zverok commented on ancient_movie.rb
> +  PRICE = Money.from_amount(1, "USD")
Может эти константы числами оставить? Виднее будет, сколько кино стоит. А Money из них уже на ходу создавать.

2016-11-18 13:06 UTC, zverok commented on netflix.rb
> +  attr_accessor :user_account
Почему accessor, а не reader?

2016-11-20 19:04 UTC, zverok requested changes

2016-11-20 19:04 UTC, zverok commented on ancient_movie.rb
> +  I18n.enforce_available_locales = false
Мне кажется, что в этом файле предыдущие 2 строчки (повторяемые и в каждом следующем) совершенно неуместно. Кроме того, чем в каждом из них `require 'movie.rb` — скорее надо в `movie.rb` за-require-ить всех наследников.

2016-11-20 19:04 UTC, zverok commented on spec/theatre_spec.rb
> +    neigbor_cinema = Theatre.new(movie_file)
let. Разберись с ним, пожалуйста!

2016-11-20 19:04 UTC, zverok commented on spec/theatre_spec.rb
> +      expect(neigbor_cinema.show(10)).to be_a(Movie)
а проч что этот тест? «покажет ну хоть шо-то»?

2016-11-20 19:04 UTC, zverok commented on spec/theatre_spec.rb
> +      expect(neigbor_cinema.when?("The Wizard of Oz")).to match(8...12)
а тесты на «такой фильм не найден»?..

2016-11-20 19:04 UTC, zverok commented on spec/theatre_spec.rb
> +      expect(neigbor_cinema.cash).to eq("$3.00")
второй тест лучше скорее выразить через матчер `expect{...}.to change....`

2016-11-20 19:04 UTC, zverok commented on spec/theatre_spec.rb
> +      expect(neigbor_cinema.take("Bank")).to eq("Transaction was accepted.")
вообще хороший тон и подход — один тест на it. почитай betterspecs.org, штоб проникнуться духом

2016-11-21 08:31 UTC, maksemuz commented on spec/theatre_spec.rb
> +      expect(neigbor_cinema.when?("The Wizard of Oz")).to match(8...12)
добавил `raise ArgumentError` в класс и проверку в спеку

2016-11-21 10:18 UTC, maksemuz commented on spec/theatre_spec.rb
> +      expect(neigbor_cinema.cash).to eq("$3.00")
исправил

2016-11-21 10:23 UTC, maksemuz commented on spec/theatre_spec.rb
> +      expect(neigbor_cinema.take("Bank")).to eq("Transaction was accepted.")
перечитаю еще 
поправил в обоих спеках для theatre и netflix

2016-11-21 18:53 UTC, zverok requested changes

2016-11-21 18:53 UTC, zverok commented on cash_box.rb
> +      raise ArgumentError, "!!! @cash_box #{@cash_box.class}" unless @cash_box
Почему так? Какие случаи он ловит, какую ошибку выдаст?

2016-11-21 18:53 UTC, zverok commented on spec/netflix_spec.rb
> +      expect(Netflix.cash).to eq('$40.00')
а с чего? если тесты независимы (что надо обеспечить!) то тут будет 0. и тест `expect {...}.to change`. 
надо про каждый тест думать как про самостоятельный, если запустить `rspec --random` они не должны сломаться (твой сломается, он ожидает, что сначала такой тест выполнился, потом сякой)

2016-11-21 19:26 UTC, maksemuz commented on cash_box.rb
> +      raise ArgumentError, "!!! @cash_box #{@cash_box.class}" unless @cash_box
Это выдавало nil, я отслеживал ошибку, приведшую к сабстрингу.
Таких было еще несколько, я их все потом удалил, а эту забыл.
Убрал.

2016-11-21 19:34 UTC, maksemuz commented on spec/netflix_spec.rb
> +      expect(Netflix.cash).to eq('$40.00')
каждый один тест - это каждый один it?
или каждый один контекст?
ни в одном руководстве я не нашел прямого утверждения за или против этого
какой ответ правильный?
почему вот тут результат приходит из предыдущего действия:
```
it 'cash' do
      expect(Netflix.cash).to eq('$40.00')
    end
```
а в следующей проверке - нет:
```
it '.show' do
      web_cinema.pay(payment)
      expect(web_cinema.show(period: 'new', genre: 'Comedy').genre).to include('Comedy')
    end
```
?

2016-11-21 19:37 UTC, maksemuz commented on spec/netflix_spec.rb
> +      expect(Netflix.cash).to eq('$40.00')
потому что результат и не должен береходить из одного it в другой
а значит, правильный ответ - каждый один отдельный тест - это it
внутри it нельзя использовать let

2016-11-22 10:11 UTC, zverok requested changes

2016-11-22 10:11 UTC, zverok commented on spec/netflix_spec.rb
> +    end
А если тесты в случайном порядке запустить (есть такая очень полезная настройка), что здесь произойдёт?

2016-11-22 10:11 UTC, zverok commented on spec/netflix_spec.rb
> +  context 'web_cinema' do
Что-то я не понял: чем этот контекст отличается от предыдущего? Почему их два? (Контексты — это обычно «когда такие-то условия...»)

2016-11-22 10:11 UTC, zverok commented on spec/theatre_spec.rb
> +  context 'Large screen' do
Тоже почему-то 2 контекста. В чём задумка?..

2016-11-22 10:41 UTC, maksemuz commented on spec/netflix_spec.rb
> +  context 'web_cinema' do
по самому первоначальному замыслу во втором кинотеатре в кассе должна была быть сумма от платежей первого и второго

2016-11-22 10:42 UTC, maksemuz commented on spec/theatre_spec.rb
> +  context 'Large screen' do
а тут в кассах суммы разные

2016-11-22 10:42 UTC, maksemuz commented on spec/theatre_spec.rb
> +  context 'Large screen' do
кстати, теперь да, наверное можно вторые части убрать

2016-11-22 10:44 UTC, maksemuz commented on spec/netflix_spec.rb
> +    end
здесь произойдет увеличение на `payment`, а не = $30
сейчас соображу как поправить

2016-11-22 11:00 UTC, maksemuz commented on spec/netflix_spec.rb
> +    end
переделал вот так:
```
    it 'cash' do
      expect {  kino_online.pay(payment) }.to change{Netflix.cash}.by(payment)
    end
```

2016-11-22 13:17 UTC, zverok approved these changes

2016-11-22 17:50 UTC, merged