Task 8 proc lambda
maksemuz/movies_rb pull request #3
Opened 2016-12-07 11:01 UTC by maksemuz

2016-12-12 12:54 UTC, zverok requested changes

2016-12-12 12:54 UTC, zverok commented on netflix.rb
> +      end
Во-первых, отладочный вывод можно было бы и убрать ;)
Во-вторых, тебе не кажется, что сложновато получилось? Кейсов-то у нас всего 2: «отфильтровать по списку фильтров (встроенных и кастомных)» и «отфильтровать блоком». Более того, по-моему они даже не взаимоисключающие (если юзер передал и то и другое, почему не отфильтровать обоими-то?). Вот метод так и должен читаться как «есть два способа отфильтровать, мы применяем один из них (или можно оба)», 3-4 строчки.

2016-12-12 12:54 UTC, zverok commented on netflix.rb
> +      "Please choose another one." unless @requests[params].nil?
Лучше бы тут отступ делать, а то тяжело читать (и в других местах тоже): 
```ruby
raise ArgumentError, "Filter name #{params} already exists."\
  "Please choose another one." unless @requests[params].nil?
```
И, кстати, такую проверку лучше через `key?` делать, лучше читается.

2016-12-12 12:54 UTC, zverok commented on netflix.rb
> +        @requests[params[:name]] = ->(item) { @requests[params[:from]].call(item, params[:arg]) }
1) в задании было: `netflix.define_filter(:newest_sci_fi, from: :new_sci_fi, arg: 2014)`
2) используй keyword arguments!

2016-12-12 13:33 UTC, maksemuz commented on netflix.rb
> +      end
1 - убрал
2 - лишнюю проверку заметил давно, забыл убрать, сейчас убрал
3 - как выглядит запрос "юзер передал и то и другое"?

2016-12-12 13:40 UTC, maksemuz commented on netflix.rb
> +      "Please choose another one." unless @requests[params].nil?
1 - отступы поправил
2 - по-моему читается вполне логично: в массиве `@requests` не найден объект по ключу `params`. А еще я не смог использовать там `.key?`, говорит `undefined method`

2016-12-12 14:14 UTC, zverok commented on netflix.rb
> +      "Please choose another one." unless @requests[params].nil?
`unless @requests.key?(params)` короче и логичнее ;) тут у тебя — так если вдуматься «выбрать из requests объект с таким названием, и проверить не пуст ли он». А с `key?` — просто проверить, что там что-то есть, ничего не вытаскивая.

2016-12-12 14:16 UTC, zverok commented on netflix.rb
> +      end
> как выглядит запрос "юзер передал и то и другое"?

```ruby
netflix.show(genre: 'Comedy') { |m| m.year.even? }
```

2016-12-12 17:50 UTC, maksemuz commented on netflix.rb
> +      "Please choose another one." unless @requests[params].nil?
да, логично, поправлю

2016-12-13 03:04 UTC, maksemuz commented on netflix.rb
> +      "Please choose another one." unless @requests[params].nil?
поправил вот так:
`unless !@requests.key?(params)`

2016-12-13 10:15 UTC, maksemuz commented on netflix.rb
> +        @requests[params[:name]] = ->(item) { @requests[params[:from]].call(item, params[:arg]) }
1 - сделал как в задании, но подозреваю, что опять не так как надо было
2 - не уверен, что использовал

2016-12-13 12:12 UTC, zverok commented on netflix.rb
> +      end
По-моему, блок теперь вообще не используется?..

2016-12-13 12:12 UTC, zverok commented on netflix.rb
> +        && @requests[parameters.keys[0]].nil?)
Какое-то ужасно сложное условие. Как так получилось?.. Давай дальше ковырять.

2016-12-15 06:36 UTC, merged